services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        tty: true # should be false in prod
        volumes: # should be removed in prod
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - path: ./environments/required.env
              required: true
            - path: ./environments/optional.env
              required: false
        depends_on:
            - db
    db:
        image: postgres:16
        env_file:
            - path: ./environments/required.env
              required: true
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: